class OpcodeTable { 

	// PTX OPCODE	
	protected static final String PTX_ADD = "add";		
	protected static final String PTX_SUB = "sub";
	protected static final String PTX_MUL = "mul";
	protected static final String PTX_MAD = "mad";	
	protected static final String PTX_MUL24 = "mul24";
	protected static final String PTX_MAD24 = "mad24";	
	protected static final String PTX_SAD = "sad";
	protected static final String PTX_DIV = "div";	
	protected static final String PTX_REM = "rem";
	protected static final String PTX_ABS = "abs";
	protected static final String PTX_NEG = "neg";
	protected static final String PTX_MIN = "min";
	protected static final String PTX_MAX = "max";
	protected static final String PTX_POPC = "popc";
	protected static final String PTX_CLZ = "clz";
	protected static final String PTX_BFIND = "bfind";
	protected static final String PTX_BREV = "brev";
	protected static final String PTX_BFE = "bfe";
	protected static final String PTX_BFI = "bfi";
	protected static final String PTX_ADDCC = "add.cc";
	protected static final String PTX_ADDC = "addc";
	protected static final String PTX_SUBCC = "sub.cc";
	protected static final String PTX_SUBC = "subc";
	protected static final String PTX_MADCC = "mad.cc";
	protected static final String PTX_MADC = "madc";
	protected static final String PTX_TESTP = "testp";	
	protected static final String PTX_COPYSIGN = "copysign";
	protected static final String PTX_FMA = "fma";	
	protected static final String PTX_RCP = "rcp";
	protected static final String PTX_SQRT = "sqrt";
	protected static final String PTX_RSQRT = "rsqrt";
	protected static final String PTX_SIN = "sin";
	protected static final String PTX_COS = "cos";
	protected static final String PTX_LG2 = "lg2";
	protected static final String PTX_EX2 = "ex2";
	protected static final String PTX_SET = "set";
	protected static final String PTX_SETP = "setp";
	protected static final String PTX_SELP = "selp";
	protected static final String PTX_SLCT = "slct";
	protected static final String PTX_AND = "and";
	protected static final String PTX_OR = "or";
	protected static final String PTX_XOR = "xor"; 	
	protected static final String PTX_NOT = "not";
	protected static final String PTX_CNOT = "cnot";
	protected static final String PTX_SHF = "shf";
	protected static final String PTX_SHL = "shl";
	protected static final String PTX_SHR = "shr";
	protected static final String PTX_MOV = "mov";
	protected static final String PTX_SHFL = "shfl";
	protected static final String PTX_PRMT = "prmt";
	protected static final String PTX_LD = "ld";
	protected static final String PTX_LDU = "ldu";
	protected static final String PTX_ST = "st";
	protected static final String PTX_PREFETCH = "prefetch";
	protected static final String PTX_PREFETCHU = "prefetchu"; 	
	protected static final String PTX_ISSPACEP = "issapcep";
	protected static final String PTX_CVTA = "cvta";
	protected static final String PTX_CVT = "cvt";
	protected static final String PTX_TEX = "tex";
	protected static final String PTX_TLD4 = "tld4";
	protected static final String PTX_TXQ = "txq";
	protected static final String PTX_SULD = "suld";
	protected static final String PTX_SUST = "sust";
	protected static final String PTX_SURED = "sured";
	protected static final String PTX_SUQ = "suq";
	protected static final String PTX_BRACEOPEN = "{";
	protected static final String PTX_BRACECLOSE = "}";
	protected static final String PTX_PREDICATE = "@";
	protected static final String PTX_PREDICATE2 = "@!";
	protected static final String PTX_LABEL = "$";	
	protected static final String PTX_BRA = "bra";
	protected static final String PTX_CALL = "call";
	protected static final String PTX_RET = "ret";
	protected static final String PTX_EXIT = "exit";
	protected static final String PTX_BAR = "bar";
	protected static final String PTX_MEMBAR = "membar";
	protected static final String PTX_ATOM = "atom";
	protected static final String PTX_RED = "red";
	protected static final String PTX_VOTE = "vote";
	protected static final String PTX_TRAP = "trap";
	protected static final String PTX_BRKPT = "brkpt";
	protected static final String PTX_PMEVENT = "pmevent";
	
	// HARP OPCODE
	protected static final String HARP_PREDICATE = "predicate";	// 2REG	
	protected static final String HARP_NOP = "nop";			// NONE
	protected static final String HARP_DI = "di";				// NONE
	protected static final String HARP_EI = "ei";				// NONE
	protected static final String HARP_TLBADD = "tlbadd";		// 3REGSRC
	protected static final String HARP_TLBFLUSH = "tlbflush";	// NONE
	protected static final String HARP_NEG = "neg";			// 2REG
	protected static final String HARP_NOT = "not";			// 2REG
	protected static final String HARP_AND = "and";			// 3REG
	protected static final String HARP_OR = "or";				// 3REG
	protected static final String HARP_XOR = "xor";			// 3REG
	protected static final String HARP_ADD = "add";			// 3REG
	protected static final String HARP_SUB = "sub";			// 3REG
	protected static final String HARP_MUL = "mul";			// 3REG
	protected static final String HARP_DIV = "div";			// 3REG
	protected static final String HARP_MOD = "mod";			// 3REG
	protected static final String HARP_SHL = "shl";			// 3REG
	protected static final String HARP_SHR = "shr";			// 3REG
	protected static final String HARP_ANDI = "andi";			// 3IMM
	protected static final String HARP_ORI = "ori";			// 3IMM
	protected static final String HARP_XORI = "xori";			// 3IMM
	protected static final String HARP_ADDI = "addi";			// 3IMM
	protected static final String HARP_SUBI = "subi";			// 3IMM
	protected static final String HARP_MULI = "muli";			// 3IMM
	protected static final String HARP_DIVI = "divi";			// 3IMM
	protected static final String HARP_MODI = "modi";			// 3IMM
	protected static final String HARP_SHLI = "shli";			// 3IMM
	protected static final String HARP_SHRI = "shri";			// 3IMM
	protected static final String HARP_JALI = "jali";			// 3IMM
	protected static final String HARP_JALR = "jalr";			// 2REG
	protected static final String HARP_JMPI = "jmpi";			// 1IMM
	protected static final String HARP_JMPR = "jmpr";			// 1REG
	protected static final String HARP_CLONE = "clone";		// 1REG
	protected static final String HARP_JALIS = "jalis";		// 3IMM
	protected static final String HARP_JALRS = "jalrs";		// 3REG
	protected static final String HARP_JMPRT = "jmprt";		// 1REG
	protected static final String HARP_LD = "ld";				// 3IMM
	protected static final String HARP_ST = "st";				// 3IMMSRC
	protected static final String HARP_LDI = "ldi";			// 2IMM
	protected static final String HARP_RTOP = "rtop";			// PREG_REG
	protected static final String HARP_ANDP = "andp";			// 3PREG
	protected static final String HARP_ORP = "orp";			// 3PREG
	protected static final String HARP_XORP = "xor";			// 3PREG
	protected static final String HARP_NOTP = "notp";			// 2PREG
	protected static final String HARP_ISNEG = "isneg";		// PREG_REG
	protected static final String HARP_ISZERO = "iszero";		// PREG_REG
	protected static final String HARP_HALT = "halt";			// NONE	
	protected static final String HARP_TRAP = "trap";			// NONE
	protected static final String HARP_JMPRU = "jmpru";		// 1REG
	protected static final String HARP_SKEP = "skep";			// 1REG
	protected static final String HARP_RETI = "reti";			// NONE
	protected static final String HARP_TLBRM = "tlbrm";		// 1REG
	protected static final String HARP_ITOF = "itof";			// 2REG
	protected static final String HARP_FTOI = "ftoi";			// 2REG
	protected static final String HARP_FADD = "fadd";			// 3REG
	protected static final String HARP_FSUB = "fsub";			// 3REG
	protected static final String HARP_FMUL = "fmul";			// 3REG
	protected static final String HARP_FDIV = "fdiv";			// 3REG
	protected static final String HARP_FNEG = "fneg";			// 2REG
	protected static final String HARP_LABEL = "label";				
	

}


